title: Data Cloning
description: Hierarchical models made easy

#baseurl:  http://localhost:4000
baseurl: https://datacloning.org
#baseurl: http://datacloning.github.io

include: [".htaccess"]
exclude: ["README.md","LICENSE.md"]
timezone:    America/Edmonton

encoding: UTF-8
markdown: kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
markdown_ext: "markdown,mkdown,mkdn,mkd,md,Rmd"

# Bootswatch theme
bswtheme: flatly
# fancy fonts on/off
fancyfonts: true
# navbar style: inverse, transparent
navbar: inverse

disqus: datacloning

author: '<a href="http://peter.solymos.org">P&eacute;ter S&oacute;lymos</a>'

ads: false

gems:
  - jekyll-feed
