title: Data Cloning
description: Hierarchical model made easy

#baseurl:  http://localhost:4000
baseurl: http://datacloning.github.io

include: [".htaccess"]
exclude: ["README.md","LICENSE.md"]
timezone:    America/Edmonton

encoding: UTF-8
markdown: kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
markdown_ext: "markdown,mkdown,mkdn,mkd,md,Rmd"

theme: cyborg
fancy: false
